'use client';

/*
 * Fetches the MCQ question set for a single topic
 * (/data/questions/<slug>.json, generated by scripts/generate_questions.py)
 * and hands it to QuizRunner. Rendered as the QUIZ mode in the main topic
 * viewer (see page.tsx).
 */

import { useEffect, useRef, useState } from 'react';
import { Loader2, HelpCircle } from 'lucide-react';
import type { QuestionSet } from '@/lib/types';
import QuizRunner from '@/components/QuizRunner';

export default function TopicQuiz({ slug }: { slug: string }) {
  const [file, setFile] = useState<QuestionSet | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const cacheRef = useRef<Map<string, QuestionSet>>(new Map());

  useEffect(() => {
    setError(null);

    const cached = cacheRef.current.get(slug);
    if (cached) {
      setFile(cached);
      setLoading(false);
      return;
    }

    setLoading(true);
    setFile(null);
    let cancelled = false;

    fetch(`/data/questions/${slug}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((data: QuestionSet) => {
        if (cancelled) return;
        cacheRef.current.set(slug, data);
        setFile(data);
        setLoading(false);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(err.message);
        setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [slug]);

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
        <span className="ml-2 text-sm text-slate-500">Loading quiz&hellip;</span>
      </div>
    );
  }

  if (error || !file) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="text-center max-w-sm">
          <HelpCircle className="w-8 h-8 text-slate-300 mx-auto mb-3" />
          <p className="text-sm font-medium text-slate-600">No quiz available yet</p>
          <p className="mt-1 text-xs text-slate-400">
            {error ? `(${error})` : 'This topic hasn’t had questions generated.'}
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto custom-scroll px-4 sm:px-8 py-5 sm:py-6">
      <QuizRunner questions={file.questions} />
    </div>
  );
}
