"""
Auto-generate /home/z/my-project/src/data/manifest.ts from all JSON files in
src/data/entries/. This makes it trivial to add new topics — just drop the
JSON files in and re-run this script.

Scans for paired <slug>.ward.json + <slug>.study.json files and emits TypeScript
imports + a TOPIC_BUNDLES record.
"""

import json
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
ENTRIES_DIR = PROJECT_ROOT / "src" / "data" / "entries"
MANIFEST_PATH = PROJECT_ROOT / "src" / "data" / "manifest.ts"


def quote_import_path(slug: str, ext: str) -> str:
    """Return a properly-quoted JS import path string, handling embedded quotes."""
    path = f"./entries/{slug}.{ext}.json"
    if "'" in path and '"' not in path:
        return f'"{path}"'
    elif '"' in path and "'" not in path:
        return f"'{path}'"
    else:
        # Contains both or neither — escape single quotes
        escaped = path.replace("'", "\\'")
        return f"'{escaped}'"


def quote_obj_key(slug: str) -> str:
    """Return a properly-quoted JS object key string."""
    if "'" in slug and '"' not in slug:
        return f'"{slug}"'
    elif '"' in slug and "'" not in slug:
        return f"'{slug}'"
    else:
        escaped = slug.replace("'", "\\'")
        return f"'{escaped}'"


def slug_to_identifier(slug: str) -> str:
    """Convert a slug like 'acute-coronary-syndrome-—-stemi' to a valid JS identifier."""
    # Replace em-dash and other non-alphanumeric with hyphen
    s = re.sub(r"[^a-zA-Z0-9-]", "-", slug)
    # Collapse multiple hyphens
    s = re.sub(r"-+", "-", s)
    # Strip leading/trailing hyphens
    s = s.strip("-")
    # Convert kebab-case to camelCase
    parts = s.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main():
    if not ENTRIES_DIR.exists():
        print(f"ERROR: entries dir not found: {ENTRIES_DIR}")
        return

    # Find all ward/study pairs
    ward_files = sorted(ENTRIES_DIR.glob("*.ward.json"))
    study_files = sorted(ENTRIES_DIR.glob("*.study.json"))

    ward_slugs = {f.name.replace(".ward.json", "") for f in ward_files}
    study_slugs = {f.name.replace(".study.json", "") for f in study_files}
    paired_slugs = ward_slugs & study_slugs

    if not paired_slugs:
        print("ERROR: no paired ward+study JSON files found")
        return

    # Sort by slug for stable output
    slugs = sorted(paired_slugs)

    print(f"Found {len(slugs)} topic bundles:")
    for s in slugs:
        print(f"  - {s}")

    # Load each ward file to get title/system/subSystem/acuity for TOPIC_LIST
    topics_meta = []
    for slug in slugs:
        ward_path = ENTRIES_DIR / f"{slug}.ward.json"
        data = json.loads(ward_path.read_text(encoding="utf-8"))
        topics_meta.append({
            "slug": slug,
            "title": data["title"],
            "system": data["system"],
            "subSystem": data.get("subSystem", ""),
            "acuity": data["acuity"],
            "identifier": slug_to_identifier(slug),
        })

    # Group by system for stable ordering
    by_system = {}
    for t in topics_meta:
        by_system.setdefault(t["system"], []).append(t)
    systems_sorted = sorted(by_system.keys())

    # Emit TypeScript
    lines = []
    lines.append("// AUTO-GENERATED by scripts/build_manifest.py — do not edit by hand.")
    lines.append("// Regenerate after adding/removing entry JSON files in src/data/entries/.")
    lines.append("")
    lines.append("import type { ClinicalEntry } from '@/lib/types';")
    lines.append("")
    lines.append("// Import all ward + study entry JSON files")
    for t in topics_meta:
        lines.append(f"import {t['identifier']}Ward from {quote_import_path(t['slug'], 'ward')};")
        lines.append(f"import {t['identifier']}Study from {quote_import_path(t['slug'], 'study')};")
    lines.append("")
    lines.append("export interface TopicBundle {")
    lines.append("  ward: ClinicalEntry;")
    lines.append("  study: ClinicalEntry;")
    lines.append("}")
    lines.append("")
    lines.append("// Slug -> bundle (every topic has both ward + study modes)")
    lines.append("export const TOPIC_BUNDLES: Record<string, TopicBundle> = {")
    for t in topics_meta:
        lines.append(f"  {quote_obj_key(t['slug'])}: {{")
        lines.append(f"    ward: {t['identifier']}Ward as unknown as ClinicalEntry,")
        lines.append(f"    study: {t['identifier']}Study as unknown as ClinicalEntry,")
        lines.append(f"  }},")
    lines.append("};")
    lines.append("")
    lines.append("export const TOPIC_LIST = Object.values(TOPIC_BUNDLES).map((b) => ({")
    lines.append("  slug: b.ward.slug,")
    lines.append("  title: b.ward.title,")
    lines.append("  system: b.ward.system,")
    lines.append("  subSystem: b.ward.subSystem || '',")
    lines.append("  acuity: b.ward.acuity,")
    lines.append("  highYield: b.ward.acuity === 'EMERGENCY' || b.ward.acuity === 'URGENT',")
    lines.append("}));")
    lines.append("")
    lines.append("// Group topics by system for the sidebar display")
    lines.append("export const TOPICS_BY_SYSTEM = TOPIC_LIST.reduce<Record<string, typeof TOPIC_LIST>>((acc, t) => {")
    lines.append("  if (!acc[t.system]) acc[t.system] = [];")
    lines.append("  acc[t.system].push(t);")
    lines.append("  return acc;")
    lines.append("}, {});")
    lines.append("")
    lines.append("// Sort systems alphabetically for predictable display")
    lines.append("export const SYSTEMS_ORDERED = Object.keys(TOPICS_BY_SYSTEM).sort();")
    lines.append("")

    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nManifest written: {MANIFEST_PATH}")
    print(f"  {len(topics_meta)} topics across {len(systems_sorted)} systems")


if __name__ == "__main__":
    main()
